### PR TITLE
Added amount of Geo from Geo Rocks and restored 2 rocks

### PR DESCRIPTION
**Pull request by Araraura**
Added the amount of Geo you'd get from each Geo Rock in the game, and restored 2 rocks that were missing from the file (one in Ancestral Mount and one in the main area of the Abyss. Hopefully I edited the correct file and didn't miss anything.

### CODE REVIEW

**Comment by ReznoRMichael** [comment]
Hey, thank you for the edit. How did you manage to get all Geo amounts for each Geo Rock? Have you typed everything one-by-one using FSMAvalonia?

Great eye for those missing Geo Rocks! I had no idea. It seems in the game/save they are treated as a single Geo Rock with some other Geo Rock, because they have the same exact ID (Geo Rock 2 and Geo Rock Abyss). It seems those two Geo Rocks are developer mistakes - bugs in the code. But OK, let's leave them as duplicates then...

You edited the auto-generated debug build file, which is ready to run, actually.

If you would like a code merge, you can try editing the file src/js/hk-database.js instead, which is the proper source file I'm building the whole code from

**Comment by Araraura** [comment]
I got all the Geo amounts manually - I used a few mods to make the process faster and individually destroyed and counted every Geo Rock in the game.

I think those 2 Geo Rocks are a bug as well, I definitely remember destroying them in a 1.4 save I did and when I checked inside the save file, they weren't counted for some reason in 1.5.

And yea I can try doing code merge. Should I revert the edits on `build/app.js` and just commit `src/js/hk-database.js`?

**Comment by ReznoRMichael** [comment]
This is crazy work. I can't even imagine. Thank you very much for the contribution and findings!

**Comment by Araraura** [comment]
@ReznoRMichael do you think you could commit the merge at some point?

**Pull request merged**
